# -*- coding: utf-8 -*-
"""california_housing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-5G4vtpOk8abX9AcA5Jgj-Oyl3iHwJc
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

data = fetch_california_housing()

print(data)

df = pd.DataFrame(data.data,columns=data.feature_names)

df.head()

df['price'] = data.target

print(df)

correlation = df.corr()

plt.figure(figsize=(10,10))
sns.heatmap(correlation,cbar=True,square=True,fmt='.1f',annot=True,annot_kws={'size':8},cmap='Blues')

X = df.drop(columns='price',axis=1)
Y = df['price']

print(X)
print(Y)

X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

model = XGBRegressor()

model_training = model.fit(X_train,Y_train)

testing_x_model = model.predict(X_train)

m2 = metrics.r2_score(Y_train,testing_x_model)

mean_model = metrics.mean_absolute_error(Y_train,testing_x_model)

print(m2)
print(mean_model)

testing_y_model = model.predict(X_test)

m22 = metrics.r2_score(Y_test,testing_y_model)

mean_modely = metrics.mean_absolute_error(Y_test,testing_y_model)

print(m22)
print(mean_modely)

plt.scatter(Y_train, testing_x_model)
plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")
plt.title("Actual Price vs Preicted Price")
plt.show()